### ISSUE TITLE
Postscribe produces an error if written Iframe has an onload attribute

### ISSUE THREAD

**Issue by mmanneva** [krux/postscribe#134] opened 2015-12-31 10:03 UTC
Hi all,

Thank you for an excellent library!

Some of our ad providers are document.write()ing iframes with onload-attributes, and this causes errors from postscribe. I've managed to reproduce the error with the following line:

        postscribe(document.body, "<iframe onload='this.src=\"http://www.google.com\"'></iframe>");

The real script doesn't write to document.body, of course, but the problem appears to be the onload attribute of the iframe, which on Google Chrome produces the following error: Uncaught SyntaxError: Unexpected token ILLEGAL.

Anyone able to help with this?

**Comment by jeffallen6767** [comment] 2016-01-04 20:02
Try:

‘this.src=….

**Comment by mmanneva** [comment] 2016-01-07 06:59
Hi, my original post does say 'this.src...' with the dot between, but it seems to be missing in the email you received.

In any case, that's not the problem.

**Comment by nikcorg** [comment] 2016-03-21 14:00
I have just run into this same issue.

**Comment by nikcorg** [comment] 2016-03-21 17:38
I've been debugging this a bit. The issue is not the `onload` attribute, but rather the escaped string inside the script assigned to the attribute. `htmlParser` seemingly correctly escapes the string inside the attribute and the produced `tokenRaw` is e.g.

    <iframe src="about:blank" onload="this.src=\"http://not-a-real-domain\""></iframe>

...and at the point of insertion the value for `chunk.actual` is 

    <iframe src="about:blank" onload="this.src=\"http://not-a-real-domain\"" data-ps-id=1 ></iframe>

However, when the string is assigned as value for `innerHTML`, the resulting markup is 

    <iframe src="about:blank" onload="this.src=\" http:="" not-a-real-domain\""="" data-ps-id="1"></iframe>

The same end result is produced when compiling the markup string by hand and assigning it to the `innerHTML` attribute. I've tested this in both Chrome Canary as well as Firefox Developer Edition with identical outcome. 

Unfortunately, I'm (so far) unable to provide a solution, but I will keep looking for one unless either someone else finds one before me or we drop postscribe for e.g. serving ads within iframes.

The complete chunk via `JSON.encode`

```
{
  "tokens": [
    {
      "tagName": "iframe",
      "attrs": {
        "src": "about:blank",
        "onload": "this.src=\\\"http://not-a-real-domain\\\""
      },
      "content": "",
      "length": 82,
      "type": "atomicTag",
      "text": "<iframe src=\"about:blank\" onload=\"this.src=\\\"http://not-a-real-domain\\\"\"></iframe>"
    }
  ],
  "raw": "<iframe src=\"about:blank\" onload=\"this.src=\\\"http://not-a-real-domain\\\"\"></iframe>",
  "actual": "<iframe src=\"about:blank\" onload=\"this.src=\\\"http://not-a-real-domain\\\"\" data-ps-id=1 ></iframe>",
  "proxy": ""
}
```

**Comment by nikcorg** [comment] 2016-03-21 20:37
A pig ugly "solution" is wrapping the original attribute contents in a `encodeURIComponent` and when writing it out wrapping it in a `eval(decodeURIComponent('<encoded attribute value here>'))`. 

E.g.
```
// when the original markup is
"<iframe src=\"about:blank\" onload=\"console.log(\\\"beep boop\\\")\"></iframe>";

// after parsing and wrapping chunk.actual becomes ->
<iframe src="about:blank" onload="eval(decodeURIComponent('console.log(%22beep%20boop%22)%3B'))" data-ps-id=1 ></iframe>
```

It "works", but isn't a real solution by any means. However, I can't find any resource detailing (for dummies) how script attributes are treated during fragment parsing. Trawling through the entire HTML5 parsing spec seems a bit overkill-ish. 

Another option would be to do some actual parsing and attaching the event handlers as proper scripts. Some sort of special treatment for event handler attributes seems the apparent solution to pursue.

**Comment by jnewman** [comment] 2016-04-23 06:21
@mmanneva try the latest version. This might be the same escaping issue as #159

**Closed** 2016-04-23 06:22 UTC
Labels: bug
