### ISSUE TITLE
Null pointer error fired on aborting postscribe execution

### ISSUE THREAD

**Issue by OleksandrShatylo** [krux/postscribe#306] opened 2016-09-01 06:20 UTC
When postscribe(null, null, "clear"); is called it seems to continue using active stream writer which is null. This leads to several null pointer exceptions.

**Comment by sethyates** [comment] 2016-09-18 06:05
hi @OleksandrShatylo,

I can't reproduce this.  I've added a unit test to this branch: https://github.com/krux/postscribe/tree/fix/issue-306.  However, either I'm not understanding your problem or the code works.  If you can reproduce, please update that unit test and file a pull request.

**Comment by sethyates** [comment] 2016-09-18 06:06
Here's a link directly to the unit test: https://github.com/krux/postscribe/blob/fix/issue-306/test/bugs/issue306.spec.js

**Comment by sethyates** [comment] 2016-09-28 22:46
Closing due to lack of a failing unit test.

**Closed by sethyates** 2016-09-28 22:46 UTC
Labels: bug

**Comment by jnewman** [comment] 2016-10-26 19:13
Removed the unit test branch as it's been a month and we don't seem to want that on master.
