### ISSUE TITLE
Problem with iframe ad code.

### ISSUE THREAD

**Issue by sajalaspl** [krux/postscribe#228] opened 2016-06-17 09:32 UTC
Sorry, no jsfiddle here. Following is the screenshot that show, iframe's "src" attribute is messed up and thus ad is not displayed.

![iframe_issue](https://cloud.githubusercontent.com/assets/3337683/16146576/6a322ff8-349c-11e6-8622-891d221bb9f6.png)

Here's the ad-code that generates it. Please check it.

`<script src="http://eas3.emediate.se/eas?cu=8272;cre=mu;js=y;pageviewid=;target=_blank" type="text/javascript"><\/script>`

**Comment by sajalaspl** [comment] 2016-09-03 06:36
Hi @sethyates, just curious if this is going to fixed anytime soon?

**Comment by sethyates** [comment] 2016-09-18 05:20
@sajalaspl not without some way of me reproducing without having to read a screenshot.  please create a failing unit test and I can look at it.

**Comment by sethyates** [comment] 2016-09-28 22:46
Closing due to lack of a failing unit test.

**Closed by sethyates** 2016-09-28 22:46 UTC
Labels: bug
