### ISSUE TITLE
Browser link is not working

### ISSUE THREAD

**Issue by jguerine** [krux/postscribe#178] opened 2016-04-27 15:26 UTC
From : https://github.com/krux/postscribe

If you just want to use the script without installing anything, use the following to load the script from cdnjs:
<script src="https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.0/postscribe.min.js"></script>

https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.0/postscribe.min.js
>>> 404.

Best

**Comment by sethyates** [comment] 2016-04-27 19:53
Duplicate of #167

**Closed by sethyates** 2016-04-27 19:53 UTC
